Desktop-version changes
Marlyn-Mayienga/Marlyn_Mayienga pull request #5
Opened 2022-05-04 20:16 UTC by Marlyn-Mayienga

# # Desktop-version changes
In this module, the following changes were made:
- made changes to the background images in the portfolio
- modified the desktop version to fit the design
- changed the styling to align the icons and text

2022-05-04 22:58 UTC, keroloussamy requested changes
Hi @Marlyn-Mayienga, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 22:58 UTC, keroloussamy commented on index.html
> +              </li>
- [ ] Kindly remove the underline from the nav links to match the Figma design.
- [ ] Kindly change the nav links color to white to match the Figma design.

Figma design
![image](https://user-images.githubusercontent.com/35535130/166837396-c0777e4e-ac26-45eb-871c-b682a9a55419.png)


Your design
![image](https://user-images.githubusercontent.com/35535130/166837439-33c5b8f9-7c4d-4a9f-8311-173246530a39.png)

2022-05-04 22:58 UTC, keroloussamy commented on index.html
> +          </section>
- [ ] Kindly change the color for the paragraph and the technologies to `#B3BAC5;` to match the Figma design.
- [ ] Kindy make the two buttons `Work` a little bit away from the accounts icons.

Figma design
![image](https://user-images.githubusercontent.com/35535130/166837929-8263f158-dfdc-4046-86c1-00591433e282.png)


Your design
![image](https://user-images.githubusercontent.com/35535130/166837892-fbea03ab-7e86-4483-8157-a1f17c7c5748.png)

2022-05-04 22:58 UTC, keroloussamy commented on style.css
> +} */
- [ ] Kindly remove the commented code, you can find it on the source tree always.

2022-05-04 22:58 UTC, keroloussamy commented on index.html
> +                    printer took a standard dummy text.
- [ ] Kindly change the color for the paragraph to `#B3BAC5` to match the Figma design.

2022-05-04 22:58 UTC, keroloussamy commented on index.html
> +        </section>
- [ ] Kindly your mobile version still looks very good, just one thing you have to work on is adding some padding from left and right on the contact section to match the Figma design.

Figma design
![image](https://user-images.githubusercontent.com/35535130/166838603-103994a0-a6fb-44fa-a255-08a39d80a194.png)

Your design
![image](https://user-images.githubusercontent.com/35535130/166838549-9112d06f-2db6-4d0e-9932-9fa03425f910.png)

2022-05-05 15:25 UTC, gemmen29 approved these changes
Hi @Marlyn-Mayienga, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 15:46 UTC, merged